// raw FFI bindings generated by bindgen
// allow non-snake-case for C types and functions
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/whisper_bindings.rs"));
